services:
  - type: web
    name: f1-dashboard-backend
    env: image
    image:
      url: docker.io/shaughnb/formula1-backend:latest
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health
    region: oregon
    plan: starter
    numInstances: 1

  - type: web
    name: f1-dashboard-frontend
    env: image
    image:
      url: docker.io/shaughnb/formula1-frontend:latest
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://f1-dashboard-backend.onrender.com
    region: oregon
    plan: starter
    numInstances: 1
